### ISSUE TITLE
Menu for user specified rule: lables output and output gap should be switched

### ISSUE THREAD

**Issue by NoLa14** [IMFS-MMB/mmb-gui-electron#10]
**Describe the bug**
In the menu for the user specified rule the names of the columns 3 and 4 (output and output gap) should be switched, so that the name of the 3rd columns is output gap and the name of the 4th column is output.

**To Reproduce**
Select one model and Taylor rule and user specified rule. Set the coefficietns for inflation to be the same as in the Taylor rule. When you type 0.5 as coefficient in the 4th column (now ouputgap) for t, you get different IR functions for the fiscal shock for both rules, although the rules seem to be the same. However, when you set the coefficient for the 3rd column (now output) to 0.5 instead (and the one for the 4th column to 0), one gets the same IR functions. Therefore, I guess the names of the columns should be switched. (Then it would also be the same order as in previous versions of the MMB)

**Desktop (please complete the following information):**
 - OS: Windows7

**Comment by fstrobel** [comment]
Hi,
I rechecked the issue, and setting the coefficients in the user speicified rule such as to mimic a different policy rule (CEE rule). 
Again, the user-specified rule can mimic the result of the CEE-rule only, when coefficients meant for the output gap are written in the column labelled output and vice versa. 
A switch in the labels for the columns should solve the bug.
