### ISSUE TITLE
No Autocorrelation and Variance for Output in NK_BGG99

### ISSUE THREAD

**Issue by btatar13** [IMFS-MMB/mmb-gui-electron#100]
**Describe the bug**
No Autocorrelation and Variance for Output in NK_BGG99 although Output does not seem to be a unit root process

**To Reproduce**
1. Run NK_BGG99 with all possible rules and monetary policy shock

**Desktop:**
 - OS: Windows 10
 - Matlab 2019a
 - Dynare 4.5.7

**Comment by gboehl** [comment]
Odd. Can you have a look yourself?

**Comment by btatar13** [comment]
Tomorrow I can have a look into.

**Comment by gboehl** [comment]
Any advancements?

**Comment by btatar13** [comment]
Working on that a bit later today. I was asked to help debug #82.

**Comment by btatar13** [comment]
I had a look into the model and ran it outside the MMB. We have indeed a unit root in the model. After a technology shock output, consumption, investment and capital do not return to their steady state values but converge to another value. Obviously agents use capital to smooth consumption and build up at the beginning additional capital to consume later the annuities, as they would do in a simple partial equilibrium infinite horizon problem. Interesting, but not unrealistic at all.

**Comment by gboehl** [comment]
Alright, thanks for looking into it. We have no means of disabling a variable only for variances and autocorrelation, and we want to keep it for the IRFs. So I'm closing this.
