### ISSUE TITLE
For FI_AINO16 IRFs to only one monetary policy shock are shown

### ISSUE THREAD

**Issue by btatar13** [IMFS-MMB/mmb-gui-electron#103]
**Describe the bug**
For FI_AINO16 IRFs to only one monetary policy shock are shown, no matter how many rules are switched on. As far as I can see, it is always for the last one from the bottom.

**To Reproduce**
1. Run FI_AINO16 with all rules and monetary Policy shock

**Desktop (please complete the following information):**
 - OS: Win10
 - Matlab 2019a
 - Dynare 4.5.7

**Comment by gboehl** [comment]
Just checked. They are produced and displayed, the output just always looks the same independently of the chosen rule. 

This indicated that the change of the MP rule is not transmitted to dynare, the error should hence be somewhere in the *.mod file. Can you have a look?

**Comment by btatar13** [comment]
In the file it is written, that monetary policy is exogenous. Therefore the interest rate equation with the MMB-coefficients is completely missing.

**Comment by gboehl** [comment]
Thanks. Can you upload a fix?

**Comment by btatar13** [comment]
I will try to do something with it later, or maybe we should leave it as it is. This seems to be a unique case that we have exogenous monetary Policy in this model

**Comment by gboehl** [comment]
I tend to agree. The idea seems to be that Finland has no control over the monetary policy... I'll upload a warning to the documentation string of the model.
