### ISSUE TITLE
GUI does not work on Windows 10 - full of error messages

### ISSUE THREAD

**Issue by btatar13** [IMFS-MMB/mmb-gui-electron#105]
**Describe the bug**
After reinstallation, as rule ids changed to rule names, I get plenty of error messages that Taylor.json could not be loaded etc. and also model errors (*.json exists but does not validate againstmodel scheme). I guess that is because rule ids were change to names

**To Reproduce**
1. Download, reinstall and run in dev mode

**Desktop:**
 - OS: Win10

**Comment by j2L4e** [comment]
What exactly is your understanding of "download, reinstall and run in dev mode"? is that `git clone (...) && npm install && npm run dev`

**Comment by j2L4e** [comment]
if you're using an external MMB path, reset it

**Comment by btatar13** [comment]
I deinstalled it, deleted the folder, downloaded it as zip from the IMFS repo directly, extracted into a different folder, npm install && npm run dev. Havent forked or cloned anything

**Comment by j2L4e** [comment]
Tests passed on CI, I tried it on windows 10 and it works perfectly fine. You didn't download the zip from the correct branch or commit or you're using an out-of-date external MMB folder.

**Comment by j2L4e** [comment]
Try downloading the installer from build.macromodelbase.com

**Comment by btatar13** [comment]
OK, the downloaded from  build.macromodelbase.com works. The zip-file I downloaded it from the master branch using the online surface as the average user would do. I will try again tomorrow to download and build it myself from the IMFS repo.

**Comment by btatar13** [comment]
**Describe the bug**
I wanted to run the dev version but it is still the same mistake which I reported a few days ago. I deinstalled, downloaded from github the zip file, unpacked, npm install and npm run dev, but as last time truckloads of mistakes of the following types show up: Error loading rule and json exists but doesn't validate against the model schema. Downloading from build.macromodelbase.com works (except Matlab testing).

**Desktop (please complete the following information):**
 - OS: Win10

**Comment by gboehl** [comment]
Closing this again. The build from build.macromodelbase.com is nothing else than a compiled version of the code in the repo.

It is a bit odd that you are unable to build since the build works for the others. It would help a lot if you would just follow the documentation Alex and I wrote and use `git`. I don't understand why you need to be the only one downloading a zip instead. 

So I assume that this is a user error.
