### ISSUE TITLE
Unimportant stuff

### ISSUE THREAD

**Issue by NoLa14** [IMFS-MMB/mmb-gui-electron#11]
**Describe the bug**
When displaying autocorrelation functions, the word “autocorrelation” goes above the button for the chart menu.

**Desktop (please complete the following information):**
 - OS: Windows7

**Comment by tmarkiv** [comment]
Not the case on MacOS.

Screenshot:
<img width="525" alt="screen shot 2019-01-23 at 15 54 31" src="https://user-images.githubusercontent.com/40387929/51615196-8c53d280-1f27-11e9-9c25-55118478b286.png">

**Comment by j2L4e** [comment]
Can't reproduce, can you provide a screenshot? What your screen resolution?
