### ISSUE TITLE
Large Variance Table is not any more on the white background part

### ISSUE THREAD

**Issue by btatar13** [IMFS-MMB/mmb-gui-electron#110]
**Describe the bug**
If the variance table is too big, then a part of it is on the grey background. PPT attached.

**Replication**
Choose two similar models, e.g. US_LTW17, US_LTW17nu, US_LTW17rot and all the common variables.
[MMB_error_table.pptx](https://github.com/IMFS-MMB/mmb-gui-electron/files/3937282/MMB_error_table.pptx)

**Comment by j2L4e** [comment]
fixed via c59f6a2
