### ISSUE TITLE
US_HL16 common shock IR doesn't appear in comparison

### ISSUE THREAD

**Issue by jisujeun** [IMFS-MMB/mmb-gui-electron#111]
**Describe the bug**
Although US_HL16 alone, the impulse response for technology shock or price markup shock appears, the IR of common shock is missing when it is compared to some other model. For example, when I try comparing US_HL16 and US_FV10, the IR of technology shock shows only the result of FV10.

**To Reproduce**
1. Compare US_HL16 with US_FV10 / FV15 / US_CMR14 (possibly some others with technology shock) with any possible policy rules
2. Compare US_HL16 with US_CMR14 / EA_SWW14 (possibly some others with price markup shock) with any possible policy rules

**Screenshots**
![2019-12-06 (2)](https://user-images.githubusercontent.com/42636696/70441314-73e39c80-1a94-11ea-97a2-2064bc377f6c.png)
![2019-12-06 (3)](https://user-images.githubusercontent.com/42636696/70441316-747c3300-1a94-11ea-8e56-1e6a304868fc.png)
![2019-12-06 (6)](https://user-images.githubusercontent.com/42636696/70441318-747c3300-1a94-11ea-8bc5-057e68ca4e8d.png)

**Desktop (please complete the following information):**
 - Window 10
 - Matlab 2019a
 - Dynare 4.5.7

**Additional context**
It seems that only the result of the first calculated model appears. When I tried to compare US_HL16 and US_PV15, as the latter is located below HL16, the result of PV15 is missing. Also when I tried to compare FV10/15 and CMR14, the same problem happened (only the result of CMR14 appeared)

**Comment by j2L4e** [comment]
What's the build date in the bottom right corner?

**Comment by jisujeun** [comment]
Yes, I did "npm install" just before working on.

Here is the error message (I also attached the screeshot for the error message):
Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
![2019-12-09 (1)](https://user-images.githubusercontent.com/42636696/70442401-8f4fa700-1a96-11ea-9309-dfb57030fc60.png)

**Comment by j2L4e** [comment]
Your other screenshots show 8 errors.

> Yes, I did "npm install" just before working on.

You need to `git pull`

**Comment by jisujeun** [comment]
I tried to do the same as before, but the error doesn't appear anymore. I guess they were accumulated as I was repeating the comparison with different models. I am not sure if it helps, but the matlab command window shows that "Note: warning(s) encountered in matlab/octave code; eps is unavailable for this model:"

I did "git pull" and then "npm install" but the result is still the same.

**Comment by j2L4e** [comment]
Can't reproduce

Please post the output of `git log -1 --oneline` (terminal)

**Comment by j2L4e** [comment]
Your fork is (very) out-of-date

either reclone from the original repo or fetch from upstream:

```
git remote add upstream https://github.com/IMFS-MMB/mmb-gui-electron.git
git fetch upstream
git checkout master
git merge upstream/master
```

**Comment by jisujeun** [comment]
Now it works! Thanks
