### ISSUE TITLE
Keyword search on the interface

### ISSUE THREAD

**Issue by cch388** [IMFS-MMB/mmb-gui-electron#116]
When I search for "Gali" on the interface, there is a blue circle keeps blinking in Estimated US, Estimated Euro Area and Other — does that mean there's no models related to Gali in these three groups? Or does it mean the interface is still searching? I use macOS 10.15 Catalina but the same thing happens to Alex, who uses Windows. Thanks!
<img width="1280" alt="Screen Shot 2019-12-11 at 11 07 48 AM" src="https://user-images.githubusercontent.com/46269849/70612574-774b6500-1c07-11ea-9bd4-f5dfd7e6ff0f.png">

**Comment by gboehl** [comment]
It means that there are no models related to Galí in these columns. Same happens if you search for "the mighty hulk". 

It is not completely necessary, but I agree that it would be nice if they stop blinking once the search is done.

**Comment by cch388** [comment]
Thanks, Gregor. Are we going to change it to no blinks? I think the previous version doesn't have blinks once the search is done (based on the screen shot in the previous version of user guide). If we are fine with blinks, I will just take a new screenshot for the user guide. Thanks!

**Comment by gboehl** [comment]
I'm leaving this to @j2L4e

**Comment by j2L4e** [comment]
Actually the blinking indicates loading during startup, it shouldnt appear when the list is empty during search.

**Comment by j2L4e** [comment]
fixed via e904f67

**Comment by cch388** [comment]
Thanks Jan.
