### ISSUE TITLE
No output when several models are selected - output produced when simulated separately 

### ISSUE THREAD

**Issue by millazar** [IMFS-MMB/mmb-gui-electron#117]
Matab2019b and Windows 10

For some combinations of models, I don't get the output, although everything works well when they are selected separately (this especially holds for EA models, for instance, when you select EA_QUEST3 and EA_CKL09). It turns out that when some of the common-model variables are missing (output in this case) - nothing pops up after the simulation. 

From my perspective, it would be better if those variables are marked as unavailable, since we cannot expect that users go to the guide and find some small note where this is explained - everything they see is that there is no result.

**Comment by j2L4e** [comment]
This has already been fixed, I think you're not using the latest version. (see https://github.com/IMFS-MMB/mmb-gui-electron/issues/111#issuecomment-563288995)

**Comment by millazar** [comment]
I wouldn't say it's the same issue.

Let me elaborate more on what I wanted to point out - different types of shocks are available to select depending on whether they exist in the model (so if you choose a model that doesn't have, let's say, a technology shock, you will not be able to select a technology shock in the shock section anymore).

However, monetary and fiscal shocks are considered to be common to every model, although for fiscal it's apparently not the case. So you would be able to select a fiscal shock in the shock section, despite the fact it doesn't exist in the model and therefore there will be no impulse responses for that model. 
Everything I'm saying is that it could be better if the fiscal shock is also shaded grey of removed from the shock section in that case, otherwise users could get confused why results are missing.

**Comment by j2L4e** [comment]
And I totally agree! 
Being able to compare even if the fiscal shock isnt supported by all models was a requirement though, so I implemented it that way.
There's a warning about that now anyway.

**Comment by millazar** [comment]
OK, great, thanks!
