### ISSUE TITLE
Fiscal shock selected - no fiscal shock in a model - no results

### ISSUE THREAD

**Issue by millazar** [IMFS-MMB/mmb-gui-electron#118]
Matlab 2019b and Windows 10

Similar to the previous issue, if you select a fiscal shock and that one is actually not available within a model  - no result will show up for that model (US_MI07AL, among others, with US_SW07, let's say).

Again, it could be better to shade fiscal shocks grey if not available, otherwise, users could get confused. But this case is less problematic than the previous one, I would say - if for other selected models you still have the outcome, you may conclude that fiscal shock is missing in one of the models you selected.

**Comment by j2L4e** [comment]
> it could be better to shade fiscal shocks grey if not available
This was discussed but isn't the desired behavior for some reason

**Comment by millazar** [comment]
OK, thank you for your answers.

**Comment by gboehl** [comment]
Reason is that we still want to have all shocks/variables selected by default. I agree that this is an inconsistency to a certain degree, but shading isn't the solution as it should always be possible to select all shocks and variables.
