### ISSUE TITLE
Unselect models -> IRF of unselected NOT shown, autocorrelation functions still shown 

### ISSUE THREAD

**Issue by AlexDece** [IMFS-MMB/mmb-gui-electron#120]
**Describe the bug**
I don't know if this is a bug or intentional.  If you click on the modelname above the IRFs, then the IRF of the model is not shown anymore (what is expected). However, the autocorellation function of this model is still in the graph (not expected).
The problem appears for non-AL models, too. 

**To Reproduce**
1. Simulate more than one model (here: 6 AL models)
2. Click on models name above the IRFs to remove them from the IRF/ACF
3. See screenshot

**Expected behavior**
I expected that the autocorrelation function of the unselected models to be removed from the ACF graph.

**Screenshots**
**screen 1:**
![problem_autocorr](https://user-images.githubusercontent.com/57352981/70626319-8260be00-1c24-11ea-87fa-ad7dbc19cbcd.PNG)

**screen 2:**
![problem_autocorr_2](https://user-images.githubusercontent.com/57352981/70626331-84c31800-1c24-11ea-8487-adae888b1a75.PNG)

**Desktop (please complete the following information):**
 - Windows
 - Matlab 2017a (screen 1), Octave 4.4.1 (screen 2)
 - Dynare 4.5.6 (screen 1), Dynare 4.5.7 (screen 2)

**Comment by AlexDece** [comment]
Also notice in screen 2 that the ACF of one model is shown for 2 or 3 periods instead of 10.

**Comment by j2L4e** [comment]
>  the autocorellation function of this model is still in the graph (not expected).

thanks, fixed via 721e172

> Also notice in screen 2 that the ACF of one model is shown for 2 or 3 periods instead of 10.

That's a bug in the model i'd say, you should file a separate issue for that
