### ISSUE TITLE
ACF of NK_IR04AL only few periods

### ISSUE THREAD

**Issue by AlexDece** [IMFS-MMB/mmb-gui-electron#121]
**Describe the bug**
Autocorrelation function of AL model **NK_IR04AL** is shorter than the periods determined before simulation. 
This holds for different period lengths and ALL monetary policy rules.
ACF of NK_IR04 is fine.
ACF of other AL models is fine (I tested NK_LWW03AL)

**To Reproduce**
1. Simulate NK_IR04AL (check ACF)
2. See error

**Expected behavior**
ACF of all periods

**Screenshots**
![nk_al_1](https://user-images.githubusercontent.com/57352981/70634087-e63db380-1c31-11ea-82b3-d36294ba8f0c.PNG)
![nk_al_2](https://user-images.githubusercontent.com/57352981/70634089-e8077700-1c31-11ea-90b7-f114d704006a.PNG)
![nk_al_3](https://user-images.githubusercontent.com/57352981/70634620-d4a8db80-1c32-11ea-8a53-a479b0caa850.PNG)

**Desktop (please complete the following information):**
Windows 10
Octave 4.4.1
Dynare 4.5.7

**Comment by gboehl** [comment]
Hm. True.

From the `output.json`:
```
...
	"data": {
		"AC": {
			"y": [1,0.940749575,0.8894850753,0.8450880773,0.803982271,0.7612268621,0.727444386,0.6945216243,0.6602946995,0.6305984967,0.604200661,0.5790707375,"_NaN_","_NaN_","_NaN_","_NaN_","_NaN_","_NaN_","_NaN_","_NaN_","_NaN_","_NaN_","_NaN_","_NaN_","_NaN_","_NaN_","_NaN_","_NaN_","_NaN_","_NaN_","_NaN_","_NaN_","_NaN_","_NaN_","_NaN_","_NaN_","_NaN_","_NaN_","_NaN_","_NaN_","_NaN_","_NaN_"],
...
```
It is clear that the AL method can lead to numerical problems/explosive behavior/etc depending on the setup (states & gain). For a different level of gain and/or differnt states everythink looks fine. 

So this behavior is somewhat expected as it is left to the user to chose states + gain accordingly.
