### ISSUE TITLE
No legend attached when graphs downloaded separately 

### ISSUE THREAD

**Issue by millazar** [IMFS-MMB/mmb-gui-electron#126]
I believe this is a general point, not related to any specific OS/Sofware product.

Once you run a simulation and obtain results (graphs), you can save them as a pdf, jpg, and similar. However, when you do it, you don’t get a legend attached. Don’t know what’s your opinion on this, is it too pedantic or not, but graphs with some colors with saying what colors actually stand for could be more useful.

**Comment by j2L4e** [comment]
fixed via 83eae6f

**Comment by AlexDece** [comment]
I updated the developer version. Now, when you click on "download ..." it works as expected. 

However, when you click "print chart" (and then I used print to pdf), still no legend appears. On the print preview you can see NO legend, so I assume, when you choose to print the chart on a piece of paper, there should be no legend as it is the case for the print to pdf option.

Here an example for print chart->print to pdf
[c.pdf](https://github.com/IMFS-MMB/mmb-gui-electron/files/3978026/c.pdf)

**Comment by gboehl** [comment]
Impressive. I never thought that anyone would use that feature ;-)

@j2L4e if there is no trivial fix for that, I think we could just savely remove the "print chart" option. I assume users are able to export to pdf and print then...

**Comment by j2L4e** [comment]
> I think we could just savely remove the "print chart" option

36878c9
