### ISSUE TITLE
Models and policy rules not shown 

### ISSUE THREAD

**Issue by cch388** [IMFS-MMB/mmb-gui-electron#127]
I just downloaded the Mac version from our website, but there are two error messages saying the models and policy rules cannot be loaded, with blue circles blinking (see attached screenshot below). I use macOS 10.15 Catalina. 

<img width="1280" alt="Screen Shot 2019-12-17 at 4 32 12 PM" src="https://user-images.githubusercontent.com/46269849/71009926-5ee9b780-20eb-11ea-99de-8c160f9f93e7.png">

**Comment by j2L4e** [comment]
You obviously renamed the app file at some point. Can you elaborate on that? It wouldn't magically choose a non-existent path

**Comment by j2L4e** [comment]
fixed via d646ecf41715ea0b0fabf8d9d45e746127140f11

**Comment by cch388** [comment]
Problem solved. My stupid mistake — I didn't rename the file but I didn't set the current path so the MMB used my previous path. Thanks for the help!
