### ISSUE TITLE
Forum reported error: “Brace indexing is not supported for variables of this type.”

### ISSUE THREAD

**Issue by millazar** [IMFS-MMB/mmb-gui-electron#130]
Do we have any idea what could be a problem here? Or I should start with questions about OS, Matlab/Dynare versions (although the compatibility test was allegedly passed), etc.?

Here is the link to the question and below is the screenshot:

https://mmb.trydiscourse.com/t/reported-error-brace-indexing-is-not-supported-for-variables-of-this-type/111

<img width="671" alt="forum" src="https://user-images.githubusercontent.com/32160336/74016615-002a1700-4993-11ea-976a-6af4d778bab4.png">

**Comment by gboehl** [comment]
Ask Jan

On 7 February 2020 10:17:38 CET, Lazar Milivojevic <notifications@github.com> wrote:
>Do we have any idea what could be a problem here? Or I should start
>with questions about OS, Matlab/Dynare versions (although the
>compatibility test was allegedly passed), etc.?
>
>Here is the link to the question and below is the screenshot:
>
>https://mmb.trydiscourse.com/t/reported-error-brace-indexing-is-not-supported-for-variables-of-this-type/111
>
>
><img width="671" alt="forum"
>src="https://user-images.githubusercontent.com/32160336/74016615-002a1700-4993-11ea-976a-6af4d778bab4.png">
> 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/IMFS-MMB/mmb-gui-electron/issues/130

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by j2L4e** [comment]
> Or I should start with questions about OS, Matlab/Dynare versions (although the compatibility test was allegedly passed), etc.?

Yes, please.

The problem's related to the rule chosen, not the model. We'd need to know that, too.

**Comment by millazar** [comment]
"Thanks for your prompt reply! You are right. It is due to the policy rule that I specified in a wrong way. Now the problem is fixed. Thank you so much for your kind help!"

It seems to be fine now.

**Comment by j2L4e** [comment]
It seems like it was a user specified rule. Mixing numeric coefficients (like `0.58`) with expression coefficients (like `0.58 * 0.33`) used to be a problem that I already fixed in early January via b9901eea41d36e049dcfd0f68a1442bbbdf6ca3f. That fix went in post-3.1.1 though, so it's only available in the nightly build currently.
