### ISSUE TITLE
MMB-Electron starting window on MacOS

### ISSUE THREAD

**Issue by tmarkiv** [IMFS-MMB/mmb-gui-electron#14]
**Describe the bug**
The starting window of MMB-Electron contains "Inspect" part. What I mean is here as a screenshot.
Tested both on my Mac and Jin's Mac (firstly I thought it is only my issue).

**To Reproduce**
Just only start the MMB-Electron

**Screenshots**
Added below

**Desktop**
 - OS: MacOs High Sierra and MacOs Yosemite tested

N.B.: Of course, by clicking on the "x" in the upper right corner it goes away and normal starting window is shown.

<img width="1292" alt="screen shot 2019-01-29 at 15 43 26" src="https://user-images.githubusercontent.com/40387929/51917803-9f134f00-23e0-11e9-8682-0336910b8b4c.png">

**Comment by j2L4e** [comment]
https://github.com/IMFS-MMB/mmb-gui-electron/blob/master/src/main/index.dev.js#L11

not a bug, it's a feature :tada: 

Only happens in the dev build. The console isn't available in production.
