### ISSUE TITLE
'mmb' command not handed over to the Matlab command window

### ISSUE THREAD

**Issue by btatar13** [IMFS-MMB/mmb-gui-electron#39]
**Describe the bug**
When selecting any model in the next branch version, the 'mmb' command is not handed over to the command window

**To Reproduce**
1. Choose any available model e.g. 'NK_BGG99', Taylor Rule, Monetary Policy Shock, Inflation
2. Hit 'Compare'

**Expected behavior**
After opening the Matlab window, the following command should be handed over and executed:

mmb('{"dynare":"C:\\dynare\\4.5.6","rules":["Taylor"],"models":["NK_BGG99"],"msr":false,"usr":false,"options":{"shocks":["interest_"],"gain":0.01,"horizon":20,"states":{}}}');exit();

Nothing happens, an empty Matlab command window is opened where you can execute any command. If copypasting the command, Dynare runs and IRFs are created.

**Comment by j2L4e** [comment]
fixed in https://github.com/IMFS-MMB/mmb-gui-electron/commit/7ef458ab05867bcd4b184a308adaa654e74b10e3
