### ISSUE TITLE
Unrecognized Matab option "batch"

### ISSUE THREAD

**Issue by btatar13** [IMFS-MMB/mmb-gui-electron#40]
**Describe the bug**
After executing any model, e.g. NK_CGG99, Taylor, Monetary Policy Shock, Inflation the impulse response is created but I get an error message displayed in the GUI:

Unrecognized Matab option "batch"

**Comment by j2L4e** [comment]
fixed in https://github.com/IMFS-MMB/mmb-gui-electron/commit/7ef458ab05867bcd4b184a308adaa654e74b10e3
