### ISSUE TITLE
US_CCF12: unexpected error with some policy rules

### ISSUE THREAD

**Issue by JTWendelborn** [IMFS-MMB/mmb-gui-electron#48]
When trying to run the model US_CCF12 with policy rules Taylor, OW08 and Coenen, the error message "Reference to non-existent field 'AUTendo_names'" (Matlab), or "structure has no member 'AUTendo_names'" (Octave) occurs. The error occurred for monetary policy, fiscal policy as well as model specific shocks (and the standard MMB variables).
Other policy rules work fine. 

The error occurred under macOS 10.13.6, for both, Matlab 2019a and Octave 5.1.0.

**Screenshots**
Under Matlab:
![Error_US_CCF12_Matlab](https://user-images.githubusercontent.com/34969113/67384019-a3941f00-f590-11e9-81b3-6ae0438169e1.png)

Under Octave:
![Error_US_CCF12_Octave](https://user-images.githubusercontent.com/34969113/67384067-bf97c080-f590-11e9-8eed-9e69b68e9b67.png)

**Comment by JTWendelborn** [comment]
For completeness, here is also the .json-file, I created for the model. (Attached as .txt, so that I can upload it here.)

[US_CCF12.txt](https://github.com/IMFS-MMB/mmb-gui-electron/files/3761864/US_CCF12.txt)

**Comment by JTWendelborn** [comment]
The same error also occurred for the same policy rules when trying to implement NK_DT12.

**Comment by j2L4e** [comment]
I dont think you should be able to run the model with these settings in the first place, because no solution can be found. I agree that it should fail gracefully, though

**Comment by JTWendelborn** [comment]
Great! Thanks for clarifying! I'll send you a pull request with the updated files shortly.
Unfortunately, Octave was not more specific.

**Comment by j2L4e** [comment]
just to clarify: Both Matlab and Octave throw the same error here, but octave doesn't support displaying a stack trace in the same way that matlab does, so it looks different. Both fail trying to read result variables from the modelbase object, because they don't exist (as no solution was found)

**Comment by gboehl** [comment]
Also resolved in one of the recent PR
