### ISSUE TITLE
Model comparison

### ISSUE THREAD

**Issue by cch388** [IMFS-MMB/mmb-gui-electron#73]
When comparing two models, sometimes only the model of which name is alphabetically listed beforehand shows the impulse response. 

Example 1:
1. Tick US_AJ16 and US_BKM12
2. Tick Taylor
3. Tick Technology shock
4. Tick Inflation
5. The interface says that technology shock (ea and eps_z) are unavailable for the models (see screenshot below).
<img width="1280" alt="Screen Shot 2019-11-25 at 3 21 01 PM" src="https://user-images.githubusercontent.com/46269849/69548360-7f649d00-0f97-11ea-95ad-2a169ab9fda0.png">
<img width="1280" alt="Screen Shot 2019-11-25 at 3 22 14 PM" src="https://user-images.githubusercontent.com/46269849/69548361-7ffd3380-0f97-11ea-80c4-87f7d2814d57.png">
6. Only US_AJ16 impulse response appears as A is alphabetically before B (see screenshot below).
<img width="1190" alt="Screen Shot 2019-11-25 at 3 02 01 PM" src="https://user-images.githubusercontent.com/46269849/69547119-4dead200-0f95-11ea-86e3-abd61c8c4d12.png">

Example 2:
1. Tick US_AJ16 and EA_ALSV06
2. Tick Taylor
3. Tick Technology shock
4. Tick Inflation
5. The interface says that technology shock (eps_z and epsz_) are unavailable for the models (see screenshot below).
<img width="1280" alt="Screen Shot 2019-11-25 at 3 25 09 PM" src="https://user-images.githubusercontent.com/46269849/69548625-f4d06d80-0f97-11ea-9ba6-0cb9ced1405a.png">
<img width="1280" alt="Screen Shot 2019-11-25 at 3 25 23 PM" src="https://user-images.githubusercontent.com/46269849/69548626-f5690400-0f97-11ea-95c5-0c173ce80f8f.png">
6. Only EA_ALSV06 impulse response appears as E is alphabetically before U (see screenshot below).
<img width="1175" alt="Screen Shot 2019-11-25 at 3 04 20 PM" src="https://user-images.githubusercontent.com/46269849/69547143-53481c80-0f95-11ea-8c30-3fe0a625f1ab.png">

But sometimes the alphabetical order doesn't matter.

Example 3:
1. Tick US_BKM12 and US_CCTW10
2. Tick Taylor
3. Tick Technology shock
4. Tick Inflation
5. Both US_BKM12 and US_CCTW10 impulse response appear (see screenshot below).
<img width="1170" alt="Screen Shot 2019-11-25 at 3 12 44 PM" src="https://user-images.githubusercontent.com/46269849/69547578-2811fd00-0f96-11ea-875f-edb5e0abc27d.png">

However, if just simulating one individual, impulse response appears anyways.

Example 4:
1. Tick  US_BKM12
2. Tick Taylor
3. Tick Technology shock
4. Tick Inflation
5. US_BKM12 impulse response appears (but it's not shown when comparing with US_AJ16).
<img width="1171" alt="Screen Shot 2019-11-25 at 3 05 30 PM" src="https://user-images.githubusercontent.com/46269849/69547166-5e02b180-0f95-11ea-840d-15e9d2eefe70.png">

**Comment by cch388** [comment]
Jonas also has the same problem btw. And I am running all these on my Macbook with MatLab.

**Comment by j2L4e** [comment]
fixed.

>The interface says that technology shock (ea and eps_z) are unavailable for the models (see screenshot below).

The way shocks are selected and passed to the backend wasn't designed for "same text/different name" kinds of shocks as this came up very recently, so the script warns about some of them not being available. It's a cosmetic thing.

**Comment by j2L4e** [comment]
Btw, these are not correctly named in master, yet. You'll need to fix #66 for that
