### ISSUE TITLE
Set up mmb

### ISSUE THREAD

**Issue by Alexle1709** [IMFS-MMB/mmb-gui-electron#74]
I just recently delete everything and pull back the newest version for testing purpose. Then, I have some weird issues that i cannot set the path for matlab in the setting even with scan or manually.
1) open by npm run dev
2) try to press scan but nothing happen
3) press find manually and choose matlab.exe in C:\Program Files\MATLAB\R2019a\bin\matlab.exe
4) nothing happen
![Screenshot (6)](https://user-images.githubusercontent.com/45760141/69556106-7d550b00-0fa4-11ea-9d05-83addbfac3e7.png)
![Screenshot (7)](https://user-images.githubusercontent.com/45760141/69556123-8514af80-0fa4-11ea-81ac-d3851268151a.png)
![Screenshot (12)](https://user-images.githubusercontent.com/45760141/69556140-8b0a9080-0fa4-11ea-8b04-51e50e2f9e87.png)
![Screenshot (13)](https://user-images.githubusercontent.com/45760141/69556169-9493f880-0fa4-11ea-8b23-bb05476508df.png)

**Comment by j2L4e** [comment]
I think I already fixed this in #71 today unless this turns out to be a different windows specific issue. Please pull the current master and report back if the problem persists

**Comment by Alexle1709** [comment]
Hi Jan,
I tried "git pull', "npm update" and even "npm install". The problem still happens. This only happen when i reinstalled the whole thing this afternoon.

**Comment by j2L4e** [comment]
Sorry for that. fixed via b1fc1b6c8fdd4f371702ed7a759aa05dd65a504e
