### ISSUE TITLE
Problem with graphical output/selection of graphs

### ISSUE THREAD

**Issue by JTWendelborn** [IMFS-MMB/mmb-gui-electron#78]
**Describe the bug**
In an earlier version, it was possible to select the graphs which are displayed in the charts of the output (IRFs) by clicking on the respective entry in the caption/legend of the charts. This feature does not work anymore for me. The caption entries are still faded out when I click on them, but the graphs displayed in the charts remain the same.

**To Reproduce**
1. Select model, eg US_SW07 and NK_BGG99
2. Select rules, eg SW07 and Taylor
3. Select a shock, eg Monetary Policy Shock
4. Click on Compare
5. Try to select single graphs in the output charts by clicking on the corresponding caption entry.

Screenshot:
![GraphError](https://user-images.githubusercontent.com/34969113/69738569-a3aab000-1136-11ea-9609-4c27d2ceaff2.png)

**Expected behavior**
I expected that the blue and red lines (for NK_BGG99, SW and NK_BGG99 Taylor) would disappear from the charts, but they don't.

**Desktop (please complete the following information):**
 - OS: MacOS 10.13
 - Matlab 2019a, Dynare 4.5.7

**Comment by j2L4e** [comment]
Reproduced. I wouldn't have thought that implementing the common legend would be such a huge pain.
