### ISSUE TITLE
Failed to open MMB on Macbooks

### ISSUE THREAD

**Issue by cch388** [IMFS-MMB/mmb-gui-electron#81]
Jonas and I downloaded MMB from http://build.macromodelbase.com/, but neither of us can open the application on our MacBooks (macOS 10.14 Mojaveto and macOS 10.15 Catalina) to start testing.

For mmb-electron-mac.zip
1. Downloaded mmb-electron-mac.zip from http://build.macromodelbase.com/
2. Un-zipped mmb-electron-mac.zip
3. Clicked the MMB icon but then Mac said the application cannot be opened (see screenshot below).
<img width="1280" alt="Screen Shot 2019-12-02 at 2 15 18 PM" src="https://user-images.githubusercontent.com/46269849/69962391-33bd7080-150e-11ea-8036-553a99e2fd40.png">
4. Clicked the question mark button but failed to run the diagnosis (see screenshot below).
<img width="545" alt="Screen Shot 2019-12-02 at 2 16 22 PM" src="https://user-images.githubusercontent.com/46269849/69962464-58b1e380-150e-11ea-8c4d-c693cfa3cb6a.png">

For mmb-electron-mac.dmg
1. Downloaded mmb-electron-mac.dmg from http://build.macromodelbase.com/
2. Opened mmb-electron-mac.dmg
3. Clicked the MMB icon, which then jumped once, but then no interface activated. Usually there should be a small black dot underneath when an application is open (see screenshot below).
<img width="529" alt="Screen Shot 2019-12-02 at 2 19 21 PM" src="https://user-images.githubusercontent.com/46269849/69962847-2654b600-150f-11ea-8dfc-d32a91c8548c.png">

Thanks!

**Comment by j2L4e** [comment]
Does the development build work?

**Comment by cch388** [comment]
Yes the developer version works.

**Comment by j2L4e** [comment]
Does the question mark give you any more detailed info on the error?

**Comment by cch388** [comment]
No, after I clicked the question mark, a new window popped out but it was just a blank window, as you can see in the second screenshot I posted earlier.

**Comment by j2L4e** [comment]
Might be related to this issue: https://github.com/electron-userland/electron-builder/issues/4179

When you unzip the file using `unzip mmb-electron-mac.zip` in the terminal (navigate to respective folder first), do the unzipped files work?

I'll investigate this, but won't be able to do so before Wednesday, unfortunately.

**Comment by j2L4e** [comment]
(for future reference) https://github.com/electron-userland/electron-builder/issues/4299

**Comment by cch388** [comment]
No, it doesn't work. :(
I first navigated to my Desktop, to where the zip file was downloaded, and then entered the unzip command you gave on my terminal. Please see the screenshot below.
<img width="770" alt="Screen Shot 2019-12-02 at 4 29 23 PM" src="https://user-images.githubusercontent.com/46269849/69971955-062df280-1521-11ea-85d6-b5a8dbfb8122.png">

**Comment by j2L4e** [comment]
Very strange, but the electron-builder people seem to be aware.
@gboehl I suggest we wait a little for an upstream fix before we start tinkering a workaround

**Comment by gboehl** [comment]
So just to see iif I get this right: 
 - the dev build works
- there is a manual fix 

Can we confirm that it is possible to manually create a working *.zip for mac? @cch388 @j2L4e could you check?

If that is the case we would still be able to go live next week, so then it would only be a problem with the automatic builds...

**Comment by cch388** [comment]
1. Yes, the developer version works

**Comment by cch388** [comment]
Yes, the developer version works.

**Comment by j2L4e** [comment]
When you `npm run build` you should be able to find mmb-electron.app in the build/mac/ folder (takes a while). Are you able to open that?

**Comment by JTWendelborn** [comment]
Hi Jan, so I (as the second Mac tester) tried to to `npm run build`, but it gave an error and except for the icon there is no output in /build. I attach both logs that the terminal gave from `npm run build`. 

[2019-12-04T11_07_10_262Z-debug.log](https://github.com/IMFS-MMB/mmb-gui-electron/files/3921508/2019-12-04T11_07_10_262Z-debug.log)

[2019-12-04T11_07_10_340Z-debug.log](https://github.com/IMFS-MMB/mmb-gui-electron/files/3921509/2019-12-04T11_07_10_340Z-debug.log)

**Comment by j2L4e** [comment]
That's a little odd because it works on travis... I'll take a look at this sometime this week

**Comment by j2L4e** [comment]
I bumped electron-builder in #83 which fixed the immediate crash on startup on 10.13.
Could you pull the latest build and check if and how behavior changes on 10.15?

**Comment by JTWendelborn** [comment]
Thanks a lot Jan! I've tried both, `.dmg` and `.zip`, on 10.13 and they both seem to work fine. I don't think that we need both builds. Most Mac programs I know are installed via a `.dmg`. From the enduser perspective, the main difference seems to be that the `.dmg` installs the mmb directly into the \Applications folder, whereas the `.zip` is just unpacked and then you can put the program in whichever folder you like...but I think you can do that from the `.dmg` as well. So I think providing one of the builds should be sufficient.

**Comment by j2L4e** [comment]
Great :+1: @cch388 can you confirm that it works on 10.15?

**Comment by cch388** [comment]
Yes, it works now on my laptop! Thanks, Jan!

**Comment by j2L4e** [comment]
Awesome :+1:
