### ISSUE TITLE
Check capturing of matlab stdout on Windows

### ISSUE THREAD

**Issue by j2L4e** [IMFS-MMB/mmb-gui-electron#87]
This screenshot suggests there's some kind of issue with capturing stdout (no version, no test output)

<img width="960" alt="screenshot" src="https://user-images.githubusercontent.com/32160336/70065412-5cfffe80-15eb-11ea-91ca-eb77e3b850c0.png">

_Originally posted by @millazar in https://github.com/IMFS-MMB/mmb-gui-electron/issues/82#issuecomment-561223634_

**Comment by j2L4e** [comment]
@millazar When you took the screenshot, were you able to simulate any model using the above configuration?

**Comment by j2L4e** [comment]
oops

**Comment by millazar** [comment]
@j2L4e I have installed the new version again to try everything once more. With regard to this issue, the answer is yes. The compatibility test for Matlab 2019b and Dynare 4.5.7 (on Windows 10) suggested that obtained values were equal to expected ones. However, this window again popped up. Additionally, I ran separate simulations for both models and got the output, as usual.

**Comment by j2L4e** [comment]
Thanks, I'll look into this

**Comment by j2L4e** [comment]
fixed via #98

**Comment by j2L4e** [comment]
You'll have to remove all matlab executables from the list and rescan or reselect them, because there was a bug with the version detection. (empty parens after the matlab path)
