### ISSUE TITLE
Naming of MMB

### ISSUE THREAD

**Issue by NoLa14** [IMFS-MMB/mmb-gui-electron#9]
**Describe the bug**
The naming of the MMB is inconsistent.
At the top if the page is on the right side „Macroeconomic Model Data Base“, on the left side "Macroeconomic Modeldatabase" and the window name is “Macromodelbase”.

**Comment by j2L4e** [comment]
Welcome!

@gboehl @fstrobel what's the preferred one?

**Comment by gboehl** [comment]
Macroeconomic Model Data Base would be consistent with the website, but I am not a huge fan of that spelling. Let us go for "Macroeconomic Model Database" which is correct and "Macromodelbase" as the colloquial short form.
