### ISSUE TITLE
After install, in 'Programs and Features' (Windows 10) it is still version 3.0.1

### ISSUE THREAD

**Issue by btatar13** [IMFS-MMB/mmb-gui-electron#95]
**Describe the bug**
In Windows 10, under Programs and Features in the Control Panel it is still version 3.0.1 

**To Reproduce**
1. Install MMB
2. Open Programs and Features under Control Panel

**Desktop:**
 - OS: Windows 10

**Comment by j2L4e** [comment]
It will change automatically once we bump the package's version number to 3.1
