### ISSUE TITLE
No Steady State for NK_DEFK17 with User Rule

### ISSUE THREAD

**Issue by btatar13** [IMFS-MMB/mmb-gui-electron#97]
**Describe the bug**
There is no steady state for the NK_DEFK17 model if the user rule is 

i_t = 0.79*i_{t-1} + 1.5*pi_t+0.5*outputgap_t

This is a somewhat aggressive central bank, yet it cannot be that there is no steady state as it should not depend on the monetary policy rule.

-------------------------------------------------------------------------------------------------

**Error message:**

Error using print_info (line 83)
Impossible to find the steady state. Either the model doesn't have a steady state, there are an infinity of steady states, or the guess values are too far from the solution

Error in steady (line 104)
    print_info(info,options_.noprint, options_);

Error in NK_DEFK17 (line 914)
steady;

Error in dynare (line 235)
evalin('base',fname) ;

Error in run_dynare_and_simulate (line 11)
  dynare(model.name);

Error in run_model_with_rules (line 13)
    result = run_dynare_and_simulate(model, rule, config.options, paths.work);

Error in mmb (line 35)
      run_model_with_rules(model, rules, config, paths);
current directory: C:\Software\MMBNew\mmb-gui-electron-master\mmb-gui-electron-master\static\mmci-cli\work\NK_DEFK17
Warning: Calling STRUCT on an object prevents the object from hiding its implementation details and should thus be avoided. Use DISP or DISPLAY to see the visible
public details of an object. See 'help struct' for more information.

-------------------------------------------------------------------------------------------------

**To Reproduce**
1. Run comparison for NK_DEFK17 with the above user rule with the monetary policy rule.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Matlab 2019a
 - Dynare 4.5.7

**Comment by gboehl** [comment]
Actually, under Octave i can find the st.st. for this rule. 

But it general it will always be the case that for some prules there is no solution. As long as you can an appropriate error message and the program keeps on running, this is not a bug.
